### ISSUE TITLE
On Ubuntu 18, arm-none-eabi-gdb-py & py3 fail to start

### ISSUE THREAD

**Issue by ilg-ul** [xpack-dev-tools/arm-none-eabi-gcc-xpack#5]
Both gdb-py and py3 fail to start:

```console
$ '/home/ilg/opt/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/8.3.1-1.2.1/.content/bin/arm-none-eabi-gdb-py' --version
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
$ export PYTHONHOME=/usr
$ '/home/ilg/opt/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/8.3.1-1.2.1/.content/bin/arm-none-eabi-gdb-py' --version
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 554, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 536, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 533, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 417, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
$ '/home/ilg/opt/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/8.3.1-1.2.1/.content/bin/arm-none-eabi-gdb-py3' --version
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f887c279480 (most recent call first):
Aborted (core dumped)
```

The original Arm binary has no problems to start, even without the `PYTHONHOME` definition:

```console
$ '/home/ilg/opt/gcc-arm-none-eabi-8-2019-q3-update/bin/arm-none-eabi-gdb-py' --version
GNU gdb (GNU Tools for Arm Embedded Processors 8-2019-q3-update) 8.3.0.20190703-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by ilg-ul** [comment]
To make things even more weird, the same binaries do start on Manjaro 18, but only after setting the Python environment:

```console
$ PYTHONHOME=/usr PYTHONPATH=/usr/lib/python2.7/ '/home/ilg/opt/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/8.3.1-1.2.1/.content/bin/arm-none-eabi-gdb-py' --version
GNU gdb (xPack GNU ARM Embedded GCC, 64-bit) 8.3.0.20190703-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ PYTHONHOME=/usr PYTHONPATH=/usr/lib/python3.7/ '/home/ilg/opt/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/8.3.1-1.2.1/.content/bin/arm-none-eabi-gdb-py3' --version
GNU gdb (xPack GNU ARM Embedded GCC, 64-bit) 8.3.0.20190703-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by ilg-ul** [comment]
Any help to diagnose this problem will be highly appreciated.

**Comment by ilg-ul** [comment]
Python support was reworked in XBB v3.2, and v9.3.1-1.1 improved the behaviour. 

An important detail is that since Python 2.7/3.7 was used during builds, exactly the same versions are required when running the binaries.
